### ISSUE TITLE
Falling letters do not work in Ukrainian language 

### ISSUE THREAD

**Issue by khoroshyy** [tux4kids/tuxtype#23] opened 2022-12-25 11:46 UTC
Hi.
I tried to use it in the Ukrainian language, but half of the menus are not readable. Letters look like rhombuses. Also in falling letters, nothing falls. 
Is it not fully localized, maybe you can give me a hint on how to fix it?
Thanks.
Petro.

**Comment by perepujal** [comment] 2022-12-29 20:23
Hi Petro,
most likely this is due to UTF-8 vs ISO8859-5 encodings in the letters/words list

 I've recoded some lists, please test, I don't know Ukrainian so I don't know if there are errors but the letters and words don't look as rhombuses anymore
What I see is some warnings about discarded words because some of their letters are not in the keyboard.list file.

The recoded files I've made are at
https://provant.freeddns.org/~pere/developing/tuxtype/Ukrainian_recoded/words/
Please test them and do any modification you need to get Ukrainian working.

HTH
Pere

**Comment by Zhuravl** [comment] 2023-02-08 18:21
Hey Petro!
I can see you started a great activity - pushing the Ukrainian translation for TuxType!

But I can see that letters in the translated files look not readable (broken) even after the re-coding!
What do you think we can do to fix this now? How can I help you with this, guys?
Illia

**Comment by Zhuravl** [comment] 2023-02-09 11:54
OK. As I understood - the main problem is in the words that should be correct and in UTF-8 encoding. I replaced the broken words and provided the PR - https://github.com/tux4kids/tuxtype/pull/25

@perepujal, thank you for highlighting the root cause of the issue!

**Comment by perepujal** [comment] 2023-02-09 22:13
Applied the merge request #25, closing this ticket, thanks :)

**Closed by perepujal** 2023-02-09 22:13 UTC
